https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport[image:https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport/badge.svg[Maven Metadata]]
https://travis-ci.org/oboehm/gdv.xport[image:https://api.travis-ci.org/oboehm/gdv.xport.svg[BuildStatus]]
https://sonarcloud.io/dashboard?id=com.github.oboehm%3Agdv-xport[image:https://sonarcloud.io/api/badges/gate?key=com.github.oboehm:gdv-xport[Quality Gate]]
https://coveralls.io/github/oboehm/gdv.xport[image:https://coveralls.io/repos/github/oboehm/gdv.xport/badge.svg[Coverage Status]]
http://www.apache.org/licenses/LICENSE-2.0.html[image:https://img.shields.io/badge/license-Apache%202.0-blue.svg[Apache License 2.0]]



= Was ist gdv.xport?

gdv.xport ist als Java-Bibliothek gestartet, die den Umgang mit dem GDV-Format erleichtert. 
Das "x" in port steht fur "im"- und "ex"-port. Die Bibliothek ist Open Source und steht unter der Apache License. 

Mit Version 3.0 gibt es neben dieser Bibliothek auch REST-Services fuer Dateien im GDV-Format. 
Die einzelnen Module sind: 

* link:lib/[*gdv-xport-lib*]: gdv.xport als Java-Bibliothek
* link:service/[*gdv-xport-service*]: gdv.xport-Services (Spring-Boot-Anwendung)

Damit aendern sich die Maven-Koordinaten für der Bibliothek in:

[source,xml]
----
<dependency>
    <groupId>com.github.oboehm</groupId>
    <artifactId>gdv-xport-lib</artifactId>
</dependency>
----



== Aehnliche Projekte

Fuer Ruby gibt es https://github.com/vendis/opengdv/[OpenGDV], einer Open-Source-Bibliothek, die unter der MIT-License steht.
Allerdings wurde diese Bibliothek schon seit laengerer Zeit nicht mehr aktualisiert.



== GIT Branching-Modell

Entwickelt wird nach http://nvie.com/posts/a-successful-git-branching-model/[A successful Git branching model] von Vincent Driessen.
Die Weiterentwicklung der aktuellen Version findet auf dem develop-Branch statt (derzeit: https://github.com/oboehm/gdv.xport/tree/develop/3.x[develop/3.x]), waehrend das letzte Release im Release-Zweig (derzeit: https://github.com/oboehm/gdv.xport/tree/release/3.x[release/3.x]) zu finden ist.



== Weitere Infos

Im https://github.com/oboehm/gdv.xport/wiki[Wiki] ist alles Wichtige zu gdv.xport zusammengefasst.
Weitere Infos wie z.B. die http://www.aosd.de/gdv.xport/apidocs/index.html[JavaDocs] finden Sie auch auf der http://www.aosd.de/gdv.xport/[Maven Projekt-Seite] .

* Wiki: https://github.com/oboehm/gdv.xport/wiki
* Projekt-Seite: http://www.aosd.de/gdv.xport/
* Xing-Gruppe: https://www.xing.com/communities/groups/datenaustausch-im-gdv-format-9756-1053093
