https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport[image:https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport/badge.svg[Maven Metadata]]
https://github.com/oboehm/gdv.xport/issues[image:https://img.shields.io/github/issues/oboehm/gdv.xport.svg[Issues]]
http://www.apache.org/licenses/LICENSE-2.0.html[image:https://img.shields.io/badge/license-Apache%202.0-blue.svg[Apache License 2.0]]



= Was ist gdv.xport?

gdv.xport ist als Java-Bibliothek gestartet, die den Umgang mit dem GDV-Format erleichtert. 
Das "x" in port steht fur "im"- und "ex"-port. Die Bibliothek ist Open Source und steht unter der Apache License. 

Ab Version 3.0 gibt es neben dieser Bibliothek auch REST-Services fuer Dateien im GDV-Format.
Die einzelnen Module sind: 

* link:lib/[*gdv-xport-lib*]: gdv.xport als Java-Bibliothek
* link:service/[*gdv-xport-service*]: gdv.xport-Services (Spring-Boot-Anwendung)
* link:deprecated/[gdv-xport-deprecated]: gdv.xport-Deprecated (aussortierte Altlasten, mit 4.0 eingeführt)

Damit aendern sich die Maven-Koordinaten für der Bibliothek in:

[source,xml]
----
<dependency>
    <groupId>com.github.oboehm</groupId>
    <artifactId>gdv-xport-lib</artifactId>
</dependency>
----



== Ähnliche Projekte

Fuer Ruby gibt es https://github.com/vendis/opengdv/[OpenGDV], einer Open-Source-Bibliothek, die unter der MIT-License steht.
Allerdings wurde diese Bibliothek schon seit laengerer Zeit nicht mehr aktualisiert.



== GIT Branching-Modell

Entwickelt wird nach http://nvie.com/posts/a-successful-git-branching-model/[A successful Git branching model] von Vincent Driessen.
Die Weiterentwicklung der aktuellen Version findet auf dem develop-Branch statt, waehrend das letzte Release im Release-Zweig (derzeit: https://github.com/oboehm/gdv.xport/tree/release/4.x[release/4.x]) zu finden ist.



== Weitere Infos

Unter link:doc/[doc] ist das Wichtigste für Entwickler zusammengefasst.
Weitere Infos wie z.B. die http://www.aosd.de/gdv.xport/apidocs/index.html[JavaDocs] finden Sie auch auf der http://www.aosd.de/gdv.xport/[Maven Projekt-Seite] .

* link:doc/release-notes.adoc[Release Notes]
* Projekt-Seite: http://www.aosd.de/gdv.xport/
* Xing-Gruppe: https://www.xing.com/communities/groups/datenaustausch-im-gdv-format-9756-1053093
