https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport-service[image:https://maven-badges.herokuapp.com/maven-central/com.github.oboehm/gdv-xport-service/badge.svg[Maven Metadata]]



= Was ist gdv-xport-service?


gdv-xport-service bildet die REST-Schnittstelle zur Java-Bibliothek "gdv-xport-lib", um auch anderen Programmiersprachen den Umgang mit dem GDV-Format zu erleichtern.
Sie vereinfacht den Export und Import dieses Datenformats und ermoeglicht die Validierung der verschiedenen Datensaetze.



== Start

gdv-xport-service ist eine Spring-Boot-Anwendung.
Sie kann als WAR-Archive auf einem Tomcat oder anderen Servlet-Container ausgerollt werden, aber auch als alleinstehende Anwendung:

* java -jar gdv-xport-service-x.y.z.jar

Als Port für die Standalone-Anwendung ist 2517 eingestellt.
Wird die Anwendung lokal gestartet, kann über

* http://localhost:2517/swagger-ui.html
* http://localhost:2517/swagger-ui.html#/datenpaket45controller

die Dokumentation der REST-Services unter "datenpaket-controller eingesehen werden.
Andere REST-Services, die in der Dokumentation angzeigt werden, sind Bestandteil der Spring-Booot-Anwendung.

Bestandteil der REST-Services ist auch eine kleine Web-Oberfläche auf Basis von Thymeleaf.
Über

* http://localhost:2517

kann damit auf die Anwendung zugegriffen werden.



== Weitere Infos

oberstes link:../README.adoc[README]
