= Bau der Anwendung

== CI-Build

.Build-Server
|===
|Server|master |develop |Konfiguration

|https://github.com/oboehm/gdv.xport/actions[GitHub]
|-
|https://github.com/oboehm/gdv.xport/actions/workflows/maven.yml[image:https://github.com/oboehm/gdv.xport/actions/workflows/maven.yml/badge.svg[Build Status]]
|s. link:../.github/workflows/maven.yml[maven.yml]

|https://coveralls.io/github/oboehm/gdv.xport[CoverAlls.io]
|https://coveralls.io/github/oboehm/gdv.xport?branch=master[image:https://coveralls.io/repos/github/oboehm/gdv.xport/badge.svg?branch=master[Coverage Status]]
|https://coveralls.io/github/oboehm/gdv.xport?branch=develop%2F4.x[image:https://coveralls.io/repos/github/oboehm/gdv.xport/badge.svg?branch=develop%2F4.x[Coverage Status]]
|`coveralls:report`

|https://codecov.io/gh/oboehm/gdv.xport[codecov.io]
|https://codecov.io/gh/oboehm/gdv.xport/branch/master[image:https://codecov.io/gh/oboehm/gdv.xport/branch/master/graph/badge.svg[codecov]]
|https://codecov.io/gh/oboehm/gdv.xport/branch/develop%2F4.x[image:https://codecov.io/gh/oboehm/gdv.xport/branch/develop%2F4.x/graph/badge.svg[codecov]]
|
|===

Der CI-Build (CI: Continuous Integration) läuft nach einem Commit und einem Push auf GitHub automatisch an.


== Manueller Bau mit Maven

Voraussetzung für den manuellen Bau der Anwendung sind:

* Java 17
* http://maven.apache.org/[Maven], mindestens in Version 3.6

Sind diese Voraussetzungen gegeben, kann die WAR-Datei für den Start als Web-Anwendung über folgendes Kommando gebaut werden:

[source]
----
mvn -DskipTests package
----

Mit der Option `-DskipTests` werden die Unit-Tests übersprungen.
Nach ca. 30 Sekunden sind dann alle Module gebaut.
Die WAR-Datei für den Start als Web-Anwendung befindet sich im Verzeichnis `service/target`.



== Bauen im Container

Sind die Voraussetzung für den manuellen Bau nicht gegeben (kein Java, kein Maven), kann die Anwendung auch über Docker gebaut werden.
Dazu gibt es auf oberster Ebene ein link:../Dockerfile[Dockerfile], mit dem die gesamte Anwendung in Docker gebaut werden kann:

[source]
----
docker build -t gdv.xport -f Dockerfile .
----

Danach kann dieser Docker-Container über

[source]
----
docker run --rm --name gdv-xport -p 2517:2517 gdv.xport
----

gestartet und unter http://localhost:2517/ aufgerufen werden.
