= Auslieferung eines neuen Releases


== Checkliste

Check-Liste für die Auslieferung eines neuen Releases:

[cols="1,2,4", options="header"]
.Check-Liste
|===
|Zeitpunkt |Aufgabe |Anmerkung

|vorher
|Release-Notes erstellen
|link:../CHANGELOG.md[CHANGELOG.md] aktualisieren

|vorher
|Release-Branch erstellen
|release-branch erstellen, developer-branch dorthin auschecken
(s.a. http://nvie.com/posts/a-successful-git-branching-model/[Git Branching-Modell]) 

|D-Day 
|Versions-Nummer aktualisieren 
|im Release-Branch überall "-SNAPSHOT" aus dem POM entfernen

|D-Day
|Finaler Release-Build und Release-Test (inkl. Signierung)
|baue alle Artefakte auf dem Release-Branch 
(`mvn -B -Prelease -Dpatterntesting.integrationTest clean install source:jar javadoc:jar gpg:sign -Dgpg.passphrase=xx`);
sollte das maven-surefire-plugin unter Java 11 mit einer NullPointerException aussteigen, den Build mit Java 8 versuchen

|D-Day
|Docker-Image bauen und pushen
|s.u.

|D-Day
|JARs auf https://oss.sonatype.org/[oss.sonatype.org] hochladen
|verwende das Skript link:../src/script/deploy.sh[src/script/deploy.sh], um die Artefakte nach
https://oss.sonatype.org/[oss.sonatype.org] hochzuladen
(aber nicht vergessen, vorher noch die VERSION-Variable in diesem Skript anzupassen).

|D-Day
|Release ins Maven Central
|nach dem Hochladen ins Staging-Repository
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-8.ReleaseIt[release it]:
selektiere "Staging Repositories" auf
https://oss.sonatype.org/[oss.sonatype.org],
drücke "Refresh" und dann "Close" und "Release".

|D-Day
|Doku und -Reports generieren
|Starte `mvn -Dpatterntesting.integrationTest clean site-deploy` starten.
Kopiere `/tmp/gdv-xport` anschließend auf die Web-Seite.

|D-Day
|release-Branch auf master mergen
|dazu lokal auf master-Branch gehen, mit release-Branch mergen und anschließend comitten;

|D-Day
|Label setzen
|`git tag gdv-xport-6.5.0` (lokal)
`git push git@github.com:oboehm/gdv.xport.git tag gdv-xport-6.5.0` (remote)

|nachher
|Tickets schließen
|https://github.com/oboehm/gdv.xport/issues[offene Tickets] schließen, die mit diesem Release bearbeitet wurden

|nachher
|Beginn mit nächstem Snapshot
|auf developer-Branch gehen, mit master mergen;
in pom.xml Version hochzählen, "-SNAPSHOT" anhängen

|nachher
|Auslieferung bekanntmachen
|Nachricht auf https://twitter.com/search?q=gdv.xport&src=typed_query&f=live[Twitter]
 
|nachher
|Maven Central prüfen
|nach ein paar Tagen: überprüfen, ob die neue Version im https://search.maven.org/search?q=gdv.xport[Central Repository] angekommen ist 
|===



== Docker-Hub

Um ein Docker-Image auf https://hub.docker.com/r/oboehm/gdv.xport zu bringen, sind folgende Schritte nötig
(s.a. https://ropenscilabs.github.io/r-docker-tutorial/04-Dockerhub.html):

* Docker-Image bauen: `docker build -t gdv.xport -f Dockerfile .`
* Image-ID ermitteln: `docker images`
* Docker-Image taggen: `docker tag <Image-ID> oboehm/gdv.xport:6.5.0`
* Docker-Image pushen: `docker push oboehm/gdv.xport:6.5.0`



== Troubleshooting

Wenn der Upload nach https://oss.sonatype.org/[oss.sonatype.org] hängenbleibt, kann man nach
https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-7b.StageExistingArtifacts[Stage Existing Artifacts]
vorgehen oder mal
https://docs.sonatype.org/display/Repository/Uploading+3rd-party+Artifacts+to+The+Central+Repository[Uploading 3rd-party Artifacts]
durchlesen.
