= Release-Notes



== 4.1 (in Planung)

* Performance-Optimierung und Verringerung des Speicher-Abdrucks (Footprint).


== 4.0.2 (14-Feb-2019)

* _fixed_: Start-Probleme mit Uberjar
  (https://github.com/oboehm/gdv.xport/issues/36[Issue #36])

== 4.0.1 (2-Feb-2019)

* _fixed_: Problem beim CSV-Export mit Sonderzeichen (Strichpunkt) behoben
  (https://github.com/oboehm/gdv.xport/issues/35[Issue #35])

== 4.0.0 (20-Jan-2019)

* Aktualisierung auf die aktuelle XML-Version von 2018.
* Bezeichner-Klasse wurde aufgeräumt und falsche bzw. nicht benötigte Konstanten entfernt.
  Ebenso wurden manche Konstanten in den Feld-Beschreibungen korrigiert.
* #_neu_#: es gibt ein neues Modul 'gdv-xport-deprecated', in der Klassen und Enumerationen verschoben wurden, die 'deprecated' sind.
  Dieses Abhängigkeit wird nur dann benötigt, wenn man noch einer dieser Klassen verwendet
* Komplexität reduziert
* Umstellung auf Java 8
* Umstellung REST-Services auf Spring-Boot 2



== 0.0.1 bis 3.2.2

Die Versionen 3.x und früher sind auf der Maven-Projekt-Seite unter http://www.aosd.de/gdv.xport/changes-report.html[changes] aufgelistet.
