= Release-Notes



== 4.1 (immer noch in Planung)

* Performance-Optimierung und Verringerung des Speicher-Abdrucks (Footprint).


== 4.0.5 (SNAPSHOT)

* _fixed_: Fehler in der Swagger-API-Dokumentation behoben
(https://github.com/oboehm/gdv.xport/issues/45[Issue #45])
* #_neu_#: rudimentäre Docker-Unterstützung
(https://github.com/oboehm/gdv.xport/issues/46[Issue #46])
* Dokumentation um Bau-Anleitung ergänzt
(https://github.com/oboehm/gdv.xport/issues/42[Issue #42])



== 4.0.4 (14-Feb-2020)

* zusätzlicher Konstruktor für Wagnisart in Satzart 0220.010 und 0221.010
(behebt https://github.com/oboehm/gdv.xport/issues/39[Issue #39])
* _fixed_: Security-Problem mit jackson-databind behoben
(https://github.com/oboehm/gdv.xport/issues/38[Issue #38])

== 4.0.3 (16-Feb-2019)

* _fixed_: Umlaut-Problem und fehlerhafter XML-Header
(https://github.com/oboehm/gdv.xport/issues/37[Issue #37])

== 4.0.2 (14-Feb-2019)

* _fixed_: Start-Probleme mit Uberjar
  (https://github.com/oboehm/gdv.xport/issues/36[Issue #36])

== 4.0.1 (2-Feb-2019)

* _fixed_: Problem beim CSV-Export mit Sonderzeichen (Strichpunkt) behoben
  (https://github.com/oboehm/gdv.xport/issues/35[Issue #35])

== 4.0.0 (20-Jan-2019)

* Aktualisierung auf die aktuelle XML-Version von 2018.
* Bezeichner-Klasse wurde aufgeräumt und falsche bzw. nicht benötigte Konstanten entfernt.
  Ebenso wurden manche Konstanten in den Feld-Beschreibungen korrigiert.
* #_neu_#: es gibt ein neues Modul 'gdv-xport-deprecated', in der Klassen und Enumerationen verschoben wurden, die 'deprecated' sind.
  Dieses Abhängigkeit wird nur dann benötigt, wenn man noch einer dieser Klassen verwendet
* Komplexität reduziert
* Umstellung auf Java 8
* Umstellung REST-Services auf Spring-Boot 2



== 0.0.1 bis 3.2.2

Die Versionen 3.x und früher sind auf der Maven-Projekt-Seite unter http://www.aosd.de/gdv.xport/changes-report.html[changes] aufgelistet.
